---
- name: Add mate desktop repositories
  apt_repository: repo={{ item }}
                  state=present
  with_items:
    - 'ppa:ubuntu-mate-dev/ppa'
    - 'ppa:ubuntu-mate-dev/trusty-mate'

- name: Install Mate Desktop
  apt: name={{ item }}
       force=yes
       state=present
  with_items:
    - ubuntu-mate-core
    - ubuntu-mate-desktop

