---
- name: Prepare system for external kernel modules
  apt: name=dkms state=present

- name: Install xorg
  apt: name=xorg state=present

- name: Install gnome-core
  apt: name=gnome-core state=present

- name: Install gnome-system-tools
  apt: name=gnome-system-tools state=present

- name: Install gnome-app-install
  apt: name=gnome-app-install state=present

- include: vboxadditions.yml
