---
- name: Add Chrome Repository
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main'
                  state=present

- name: Add Chrome repo key
  apt_key: url='https://dl-ssl.google.com/linux/linux_signing_key.pub'
           state=present

- name: Install Chrome Stable
  apt: name=google-chrome-stable
       force=yes
       state=latest
