---
- name: Download Eclipse
  get_url: url=http://ftp.halifax.rwth-aachen.de/eclipse//technology/epp/downloads/release/kepler/SR2/eclipse-jee-kepler-SR2-linux-gtk-x86_64.tar.gz
           dest=/opt/eclipse-jee-kepler-SR2-linux-gtk-x86_64.tar.gz

- name: Extract Eclipse
  shell: tar -xzf /opt/eclipse-jee-kepler-SR2-linux-gtk-x86_64.tar.gz -C /opt/
         creates=/opt/eclipse

- name: Create Eclipse Desktop Entry
  copy: src=eclipse.desktop
        dest=/usr/share/applications
        mode=0644
