---
sudo: false
- name: Install GVM
  shell: curl -s get.gvmtool.net | bash
         creates=~/.gvm

- name: Install Groovy
  shell: gvm install groovy {{ groovy_version  }}
         creates=~/.gvm/groovy/{{ groovy_version  }}
         executable=/bin/bash

- name: Install Grails
  shell: gvm install grails {{ grails_version  }}
         creates=~/.gvm/grails/{{ grails_version  }}
         executable=/bin/bash

- name: Install Gradle
  shell: gvm install gradle {{ gradle_version  }}
         creates=~/.gvm/gradle/{{ gradle_version  }}
         executable=/bin/bash
