---
- name: Create 'opt' Directory
  sudo: "{{vagrant_run}}"
  sudo_user: "{{user}}"
  file: path=~/opt
        state=directory

- name: Download Intellij Idea
  get_url: url=http://download.jetbrains.com/idea/ideaIU-{{idea_version}}.tar.gz
           dest=/opt/ideaIU-{{idea_version}}.tar.gz

- name: Extract Intellij Idea
  shell: tar -xzf /opt/ideaIU-{{idea_version}}.tar.gz -C /opt
         creates=/opt/idea-IU-{{idea_build}}

- name: Create Link to Intellij Idea
  file: path=/opt/idea
        force=yes
        state=link
        src=/opt/idea-IU-{{idea_build}}

- name: Copy Intellij Idea User Defaults
  sudo: "{{vagrant_run}}"
  sudo_user: "{{user}}"
  copy: src=idea-defaults.tar.gz
        dest=~/opt

- name: Install Intellij Idea User Defaults
  sudo: "{{vagrant_run}}"
  sudo_user: "{{user}}"
  shell: tar -xzf ~/opt/idea-defaults.tar.gz -C ~/
         creates=~/.IntelliJIdea13/

- name: Create Intellij Desktop Entry
  copy: src=intellij-idea.desktop
        dest=/usr/share/applications
        mode=0644
