---
- name: Install Python virtualenv
  apt: name=python-virtualenv state=present

- name: Create Python virtualenv
  sudo: false
  command: virtualenv ~/.venv

- name: Aktivate virtualenv in User Shell
  sudo: false
  lineinfile: dest=~/.profile
              line='. ~/.venv/bin/activate'
              state=present
