---
- name: Install Python virtualenv
  apt: name=python-virtualenv state=present

- name: Create Python virtualenv
  sudo_user: "{{ user  }}"
  command: virtualenv ~/.venv

- name: Aktivate virtualenv in User Shell
  sudo_user: "{{ user }}"
  lineinfile: dest=~/.profile
              line='. ~/.venv/bin/activate'
              state=present
